name: Build C++ Console App

# Ejecuta el workflow en cada push o pull request a la rama master
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Paso 1: Chequear el código del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 2: Configurar Visual Studio 2022
    - name: Set up Visual Studio
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
        toolset: host=x64

    # Paso 3: Compilar la solución del proyecto
    - name: Build the solution
      run: |
        msbuild Proyecto0-ED.sln /p:Configuration=Release

    # Paso 4: Subir el ejecutable como un artifact
    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: Proyecto0-ED-executable
        path: Proyecto0-ED/x64/Release/Proyecto0-ED.exe
